# Generated by Django 5.2.7 on 2025-10-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_farmer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sowing', 'Sowing'), ('harvest', 'Harvest'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for a window', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('farmer', models.ForeignKey(blank=True, help_text='If blank, this event is global', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
