# Generated by Django 5.2.7 on 2025-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_importantdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdate',
            name='recurrence',
            field=models.CharField(blank=True, help_text='Optional recurrence rule (RRULE)', max_length=512),
        ),
    ]
